apiVersion: v1
kind: Service
metadata:
  name: arogya-web
  namespace: clinical-security
  labels:
    app.kubernetes.io/name: arogyaraksha
    app.kubernetes.io/component: web
    app.kubernetes.io/part-of: arogyaraksha-cns
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: arogyaraksha
    app.kubernetes.io/component: web
